### PR TITLE
changed css property

### PR DESCRIPTION
**Pull request by kambayashia**
'background:' overwrite many properties.

before
```
.class-name {
    background: url('data:image/png;.....');
}
```

after
```
.class-name {
    background-image: url('data:image/png;.....');
}
```

### CODE REVIEW

**Comment by heldr** [comment]
Hi, could you please update the tests?

https://travis-ci.org/heldr/datauri/jobs/61119118

**Comment by kambayashia** [comment]
:ok_hand:

**Comment by kambayashia** [comment]
updated test.

**Comment by heldr** [comment]
Thanks for the contribution :tea:

**Comment by kambayashia** [comment]
:+1:

**Pull request merged**
